# Generated by Django 3.2.2 on 2021-05-19 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumini', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='aluminious',
            new_name='aluminies',
        ),
    ]
