# Generated by Django 3.2.2 on 2021-05-19 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumini', '0003_alter_aluminies_alumini_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluminies',
            name='alumini_image',
            field=models.ImageField(blank=True, default='dpic.png', null=True, upload_to=''),
        ),
    ]
