# Generated by Django 3.1.5 on 2021-05-20 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumini', '0004_alter_aluminies_alumini_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluminies',
            name='alumini_image',
            field=models.ImageField(blank=True, default='img/dpic.png', null=True, upload_to=''),
        ),
    ]
