# Generated by Django 3.1.5 on 2021-05-20 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumini', '0005_auto_20210520_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluminies',
            name='alumini_image',
            field=models.ImageField(blank=True, default='dpic.png', null=True, upload_to=''),
        ),
    ]
