# Generated by Django 3.1.5 on 2021-05-20 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumini', '0006_auto_20210520_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluminies',
            name='alumini_image',
            field=models.ImageField(blank=True, default='images/dpic.png', null=True, upload_to='images'),
        ),
    ]
