# Generated by Django 3.1.5 on 2021-05-31 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumini', '0007_auto_20210520_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluminies',
            name='address',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='aluminies',
            name='college',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='aluminies',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aluminies',
            name='h_education',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aluminies',
            name='phone',
            field=models.IntegerField(max_length=10, null=True),
        ),
    ]
