# Generated by Django 3.1.5 on 2021-05-31 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumini', '0008_auto_20210531_2322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aluminies',
            old_name='h_education',
            new_name='education',
        ),
    ]
