# Generated by Django 3.2.2 on 2021-06-29 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumini', '0010_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
