# Generated by Django 3.1.5 on 2021-07-01 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumini', '0011_delete_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluminies',
            name='alumini_image',
            field=models.ImageField(blank=True, default='img/dpic.png', null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='aluminies',
            name='phone',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
