# Generated by Django 3.1.5 on 2021-07-04 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumini', '0012_auto_20210702_0249'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluminies',
            name='InSchool',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
