# Generated by Django 3.1.5 on 2021-07-06 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumini', '0013_aluminies_inschool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluminies',
            name='phone',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
    ]
