# Generated by Django 3.1.5 on 2021-09-06 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumini', '0014_auto_20210905_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluminies',
            name='phone',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
