# Generated by Django 3.1.5 on 2021-07-06 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumini', '0015_auto_20210707_0241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluminies',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
